export const ADD_TAB = "ADD_TAB";
export const CLOSE_TAB = "CLOSE_TAB";
export const ACTIVATE_TAB = "ACTIVATE_TAB";
export const DEACTIVATE_TAB = "DEACTIVATE_TAB";
export const UPDATE_TAB = "UPDATE_TAB";
export const UPDATE_ACTIVE_TAB = "UPDATE_ACTIVE_TAB";
export const SET_TABS = "SET_TABS";

export const ADD_PASSWORD = "ADD_PASSWORD";
export const REMOVE_PASSWORD = "REMOVE_PASSWORD";
export const UPDATE_PASSWORD = "UPDATE_PASSWORD";
export const SET_PASSWORDS = "SET_PASSWORDS";

export const ADD_BOOKMARK = "ADD_BOOKMARK";
export const REMOVE_BOOKMARK = "REMOVE_BOOKMARK";
export const SET_BOOKMARKS = "SET_BOOKMARKS";

export const ADD_SEARCH_HISTORY = "ADD_PASSWORD";
export const REMOVE_SEARCH_HISTORY = "REMOVE_SEARCH_HISTORY";
export const SET_SEARCH_HISTORY = "SET_SEARCH_HISTORY";
